import { DocumentType, DocumentTypeTemplate } from "@/types/models";

export const documentTemplates: DocumentTypeTemplate[] = [
  {
    id: DocumentType.PERJANJIAN_KERJASAMA,
    name: "Perjanjian Kerjasama",
    description: "Dokumen legal untuk kerja sama antara dua pihak",
    fields: [
      { key: "judul", label: "Judul", type: "text", placeholder: "Masukkan judul dokumen", required: true },
      { key: "perjanjian", label: "Jenis Perjanjian", type: "text", placeholder: "Masukkan jenis perjanjian", required: true },
      { key: "pihak1", label: "Pihak 1", type: "text", placeholder: "Masukkan nama pihak pertama", required: true },
      { key: "pihak2", label: "Pihak 2", type: "text", placeholder: "Masukkan nama pihak kedua", required: true },
      { key: "jabatan1", label: "Jabatan Pihak 1", type: "text", placeholder: "Masukkan jabatan pihak pertama", required: false },
      { key: "jabatan2", label: "Jabatan Pihak 2", type: "text", placeholder: "Masukkan jabatan pihak kedua", required: false },
      { key: "deskripsi", label: "Ruang Lingkup Kerjasama", type: "textarea", placeholder: "Masukkan deskripsi ruang lingkup kerjasama", required: true },
      { key: "durasi", label: "Durasi Kerjasama", type: "text", placeholder: "Contoh: 1 tahun", required: false },
      { key: "tanggal", label: "Tanggal", type: "date", placeholder: "", required: true },
      { key: "tempatPenandatanganan", label: "Tempat Penandatanganan", type: "text", placeholder: "Masukkan tempat penandatanganan", required: false },
    ],
  },
  {
    id: DocumentType.PERJANJIAN_JUAL_BELI,
    name: "Perjanjian Jual Beli",
    description: "Dokumen legal untuk transaksi jual beli",
    fields: [
      { key: "judul", label: "Judul", type: "text", placeholder: "Masukkan judul dokumen", required: true },
      { key: "perjanjian", label: "Objek Jual Beli", type: "text", placeholder: "Masukkan objek yang diperjualbelikan", required: true },
      { key: "pihak1", label: "Penjual", type: "text", placeholder: "Masukkan nama penjual", required: true },
      { key: "pihak2", label: "Pembeli", type: "text", placeholder: "Masukkan nama pembeli", required: true },
      { key: "nilai", label: "Nilai Transaksi", type: "text", placeholder: "Masukkan nilai transaksi", required: true },
      { key: "deskripsi", label: "Deskripsi Barang/Jasa", type: "textarea", placeholder: "Masukkan deskripsi detail barang/jasa", required: true },
      { key: "tanggal", label: "Tanggal", type: "date", placeholder: "", required: true },
      { key: "penyelesaianSengketa", label: "Penyelesaian Sengketa", type: "select", placeholder: "Pilih metode penyelesaian sengketa", required: false, options: ["Musyawarah", "Mediasi", "Arbitrase", "Pengadilan"] },
    ],
  },
  {
    id: DocumentType.PERJANJIAN_SEWA,
    name: "Perjanjian Sewa",
    description: "Dokumen perjanjian sewa properti atau barang",
    fields: [
      { key: "judul", label: "Judul", type: "text", placeholder: "Masukkan judul dokumen", required: true },
      { key: "perjanjian", label: "Objek Sewa", type: "text", placeholder: "Masukkan objek yang disewakan", required: true },
      { key: "pihak1", label: "Pemilik", type: "text", placeholder: "Masukkan nama pemilik", required: true },
      { key: "pihak2", label: "Penyewa", type: "text", placeholder: "Masukkan nama penyewa", required: true },
      { key: "alamat", label: "Alamat Objek", type: "textarea", placeholder: "Masukkan alamat lengkap objek sewa", required: true },
      { key: "nilai", label: "Nilai Sewa", type: "text", placeholder: "Masukkan nilai sewa", required: true },
      { key: "durasi", label: "Durasi Sewa", type: "text", placeholder: "Contoh: 12 bulan", required: true },
      { key: "deskripsi", label: "Ketentuan Sewa", type: "textarea", placeholder: "Masukkan ketentuan sewa", required: true },
      { key: "tanggal", label: "Tanggal Mulai", type: "date", placeholder: "", required: true },
    ],
  },
  {
    id: DocumentType.SURAT_KUASA,
    name: "Surat Kuasa",
    description: "Dokumen pemberian kuasa dari satu pihak ke pihak lain",
    fields: [
      { key: "judul", label: "Judul", type: "text", placeholder: "Masukkan judul dokumen", required: true },
      { key: "perjanjian", label: "Jenis Kuasa", type: "text", placeholder: "Masukkan jenis kuasa", required: true },
      { key: "pihak1", label: "Pemberi Kuasa", type: "text", placeholder: "Masukkan nama pemberi kuasa", required: true },
      { key: "pihak2", label: "Penerima Kuasa", type: "text", placeholder: "Masukkan nama penerima kuasa", required: true },
      { key: "deskripsi", label: "Hal yang Dikuasakan", type: "textarea", placeholder: "Masukkan detail hal yang dikuasakan", required: true },
      { key: "tanggal", label: "Tanggal", type: "date", placeholder: "", required: true },
      { key: "npwp", label: "NPWP Pemberi Kuasa", type: "text", placeholder: "Masukkan NPWP (opsional)", required: false },
      { key: "tempatPenandatanganan", label: "Tempat Penandatanganan", type: "text", placeholder: "Masukkan tempat penandatanganan", required: true },
    ],
  },
  {
    id: DocumentType.PERJANJIAN_KERAHASIAAN,
    name: "Perjanjian Kerahasiaan (NDA)",
    description: "Dokumen perjanjian untuk menjaga kerahasiaan informasi",
    fields: [
      { key: "judul", label: "Judul", type: "text", placeholder: "Masukkan judul dokumen", required: true },
      { key: "pihak1", label: "Pihak Pemberi Informasi", type: "text", placeholder: "Masukkan nama pihak pemberi informasi", required: true },
      { key: "pihak2", label: "Pihak Penerima Informasi", type: "text", placeholder: "Masukkan nama pihak penerima informasi", required: true },
      { key: "deskripsi", label: "Informasi Rahasia", type: "textarea", placeholder: "Masukkan deskripsi informasi rahasia", required: true },
      { key: "durasi", label: "Jangka Waktu Kerahasiaan", type: "text", placeholder: "Contoh: 5 tahun", required: true },
      { key: "tanggal", label: "Tanggal", type: "date", placeholder: "", required: true },
      { key: "hukumYangBerlaku", label: "Hukum yang Berlaku", type: "text", placeholder: "Masukkan yurisdiksi hukum yang berlaku", required: false },
    ],
  },
];
